package com.gridbetjavaa.gridbetjavaa.model;

import jakarta.persistence.*;

@Entity
@Table(name = "game")
public class Game {

    //Use the id generated by the data provider GRID
    @Id
    private Long id;
    @Column(name = "email",nullable=false)
    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    public String getName() {
        return name;
    }

    public void setName(String email) {
        this.name = email;
    }

    // Default constructor without any arguments
    public Game() {
    }

    public Game(String name, Long id){
        this.name = name;
        this.id = id;
    }
}